### ISSUE TITLE
Still confused on one small thing.

### ISSUE THREAD

**Issue by SilverMantis** [EndLone/MCDE#11]
Hello! I had sent an issue into this github page yesterday due to which most of the glitches I was having were resolved (and thanks a bunch for the help!), but I am still confused on one small thing I didn't think to ask, how can I disable the enchants of other mods (other than mcdx mods) from appearing in the runic table thru the config file? 

I opened up the config and checked its other files as well, but I can't seem to find where to disable enchants from other mods.

I'd really appriciate some help on finding where to fix this. Thanks!

**Comment by EndLone** [comment]
In the config/mcde there's a config. In it there are two settings that you need for disabling enchantments from appearing in the tables.
The first one is list type (by default is set to "DENY", which will make the other setting act as a blacklist)
The second one is the list itself (by default has unbreaking and mending, so that they don't appear in the tables). You can block whole mods worth of enchants if you add "modID:*" (this will block every enchant in the mod from appearing)

**Comment by SilverMantis** [comment]
just found it, I guess I wasn't being too attentive when reading the config lol, thanks a bunch!

**Comment by 915Prophet** [comment]
In this same vein of questioning, is it possible to have both an enchant blacklist (for enchants such as mending and unbreaking) AND a whitelist for enchants from other mods such as the Wizards mod or twilight forest?

ALSO secondarily, is there a way to disable to vanilla enchanting or other sources of enchanting from other mods through this one, or am I barking up the wrong tree with that?

**Comment by EndLone** [comment]
You have to choose between a blacklist or a whitelist in the config. Making both a blacklist (a list that blocks everything inside it) and a whitelist (a list that allows only what's inside of it to be generated) wouldn't make much sense from the logical standpoint.

In the same config, the enchantment table is disabled by default (you can still craft it and while in Creative mode - open it). There are more settings that you can tweak to make the mod work however you want, so i recommend playing around with that.
