### ISSUE TITLE
Melee weapon enchantments on ranged weapons

### ISSUE THREAD

**Issue by slammaja** [EndLone/MCDE#18]
Hi, for some reason I am getting only melee enchantments on bows and crossbows. I thought mod "Projectile Damage Atrribute" might be causing this,  but the problem persists after removing said mod.

**Comment by EndLone** [comment]
Hello, can you provide some screenshots, which enchantments are generated and a list of mods?

**Comment by slammaja** [comment]
Here is modlist and some screenshots. There's crossbow in roll bench.
![2023-08-20_17 12 04](https://github.com/EndLone/MCDE/assets/12775695/386b6db5-ee96-49a0-bdec-554c272f0d14)
![2023-08-20_17 12 06](https://github.com/EndLone/MCDE/assets/12775695/289e3f9a-dc9c-4aec-8587-62bf2ddb4c34)
![2023-08-20_17 12 11](https://github.com/EndLone/MCDE/assets/12775695/0d038993-a5fc-4adb-b377-0e5a5143cf59)
![2023-08-20_17 11 58](https://github.com/EndLone/MCDE/assets/12775695/c93a1cab-3583-4427-8240-a60701257dd6)
![2023-08-20_17 12 00](https://github.com/EndLone/MCDE/assets/12775695/df4d6ae1-9afd-4e56-8690-14becc8b6877)
![2023-08-20_17 12 01](https://github.com/EndLone/MCDE/assets/12775695/07beacb4-4428-40e4-9903-e62b439c543a)

![2023-08-20_17 11 56](https://github.com/EndLone/MCDE/assets/12775695/9d8a7323-7435-4277-98b1-c973e3919609)
[modlist.txt](https://github.com/EndLone/MCDE/files/12388506/modlist.txt)

**Comment by EndLone** [comment]
It seems that you have mods which add their own enchantments. We do not tamper with any enchantments and their targets (Sharpness -> Sword, Efficiency -> Pickaxe etc) as our mod itself checks which enchantments fit what items. The behaviour you're expiriencing with vanilla enchantments is caused by some other mod that is tampering with vanilla enchantments item targets. For the modded enchantments however, this can be the cause of the enchantment itself having bows/crossbows as one of their targets (or the same mod that tampers with vanilla enchantments working with the modded ones)

**Comment by slammaja** [comment]
The only mod changing enchanting behavior/rules I can think of is Enchancement, but after removing it problem is still there. I will try tinkering with other mods then.
